### ISSUE TITLE
HexKinetics Entirely Broken

### ISSUE THREAD

**Issue by LlamaSageR** [HexxyCraft/modpack#100]
Namely, the ability to swap any two blocks with no regards for ambit via Greater Translocation (including Bedrock and End Portals among others) and the potential for infinite loop-unrolling via Greater Impulse (No minimum cost), among other issues that are possibly present.

The current course of action is the removal of HexKinetics until it is properly patched and tested.

**Comment by maraxin** [comment]
a) Greater impulse was removed, so I am not sure what you're on
b) Couldn't you just.... disable this spell?

**Comment by Sonunte** [comment]
I have a few questions regarding your statement. Firstly, when you mention 'swapping any two blocks,' could you please clarify what you mean? According to my understanding, Greater Translocation should only allow for moving blocks or potentially destroying them, rather than swapping them. Secondly, when you refer to 'Greater Impulse,' I assume you are referring to Twokai's Ideal Condition. How does the lack of minimal cost in this condition enable infinite loop-unrolling? If my assumption is correct, it's worth noting that blink also doesn't have minimal cost. (If you actually meant Propulsion by mentioning Greater Impulse, then it certainly does have minimal cost.) I would greatly appreciate it if you could address these questions, as it would help me in improving HexKinetics.

**Comment by object-Object** [comment]
> a) Greater impulse was removed, so I am not sure what you're on
> b) Couldn't you just.... disable this spell?

The entire mod has been consistently problematic and clearly has had very little testing. Until this improves, it's not suitable for a production server, even one like HexxyCraft.

**Comment by walksanatora** [comment]
i mean ... HexTweaks has little to no testing (I only found out reroll being broken once the server opened)

**Comment by LlamaSageR** [comment]
A failure of my own testing. Regardless, HexTweaks has not had as major an issue as "move any immovable block."
