### ISSUE TITLE
Add Mine Treasure

### ISSUE THREAD

**Issue by object-Object** [HexxyCraft/modpack#157]
https://modrinth.com/datapack/mine-treasure
> allows for more possible loot without having to expand the borders again

**Comment by LlamaSageR** [comment]
Additional/alternative sources of loot is nice, but given the description of the mod,

> In Mine Treasure there are over 100+ custom items, as well as over 200+ advancements added to the game and many new ways to make every biome-type feel more special.

adding this much extra "loot" is a bit excessive of a change. Not to mention how a great deal of the custom items are "Super enchanted gear!" and potion effect sources. In general, it is balanced around the fact that "it is balanced because it is really rare," which isn't balanced at all. Not to mention the trigger for getting the loot is just mining stone-based blocks.

Here are some of the egregious examples
* Better than Netherite gear.
* Spawn Eggs, including: Iron Golems, Pillagers, Wither Skeletons
* Spawners
* Sculk Shriekers
* Reinforced Deepslate
* Infinite Fuel crafting stations (Smoker, Brewing stand, etc.)
* Dragon Egg
* Nether Star
