### ISSUE TITLE
Add CPM/Figura/Ears

### ISSUE THREAD

**Issue by object-Object** [HexxyCraft/modpack#43]

**Comment by LlamaSageR** [comment]
Should we add all three? Regardless, adding Ears at the very least would be ideal, especially since it is, according to the mod description, "a much more lightweight patch with no usage of third-party servers and is completely open source."

I am a bit worried about these third-party servers for the other mods, and Figura I know can be used to do some *very* silly things (though there's some variety of permissions in it to disable that for select players).

These are my main concerns, though I will admit I lack experience. I'll defer judgement to you.
