### ISSUE TITLE
Add Twigs

### ISSUE THREAD

**Issue by object-Object** [HexxyCraft/modpack#71]
https://modrinth.com/mod/twigs

**Comment by LlamaSageR** [comment]
Twigs was reworked in the latest update to be mostly driven by world-generation (Silt, twigs, seashells, etc). Given the small border size, having a large number of world-generated features is unwise, and it would take a lot of effort put into introducing viable recipes for all of them. This is one of the original reasons why I excluded it, not to mention the heightened difficulties now that the entire world has been generated. 

Additionally, the majority of blocks were redundant with other mods, namely the Granite, Tuff, and Calcite suite of blocks introduced by Create and Architect's Palette, among others. I elected to remove it due to the removal of many more of the unique blocks it had prior to the update (3.0.0 specifically, it removed the required library mod and a lot of blocks with it).
