### ISSUE TITLE
Some mod suggestions for Hexxycraft:

### ISSUE THREAD

**Issue by melechdaviid** [HexxyCraft/modpack#98]
*Simply Backpacks
*Sound Physics
*Ambient Sounds
*I'd like to say Biomes You'll Go, but that needs new worldgen.
*Sleeping Bags
*Campion
*Bewitchment (worldgen issue again)
*Handcrafted (furniture mod)

**Comment by LlamaSageR** [comment]
1. Simply Backpacks invalidates every other form of portable storage by simply being stronger (Shulker Boxes, Bundles, Sacks, Packages, etc.) and trivializes the cost of GTP since storage held in a Trinkets slot cannot be removed.

2. Sound Physics Remastered is an interesting mod, and it has compatibility with Simple Voice Chat (with some configuring). I myself would enjoy it. If there is more support for it with the others, it could be added as an optional mod, default set to false as it is largely an issue of personal taste. Regardless, it can always be installed on an individual basis.

3. Ambient Sounds falls under the same category as above, though Charmonium would likely fare better. 

4. BYG, regardless of the current worldgen, would be a bad addition. It simply adds more "stuff," without substance or purpose. While it is certainly a better world generation mod than Biomes O' Plenty, it still fails to achieve any strong impressions besides adding more "stuff" to flood your chests and inventories (most of which is nonrenewable). This also disregards the issues with the limited world border, where more biomes makes it less likely to have everything that is necessary for gameplay. These are the reasons why it was excluded from the original draft of the modpack.

5. Suggested in issue #62, Sleeping Bags is a nice utility when out and about. Should be a good addition.

6. Campanion (could not find a mod titled "Campion") simply does not belong in the modpack. As a mod focused around adventure and exploration, providing tools for enhanced portable storage and traversal along with decoration to boot, Campanion is simply too "large" for such a small world. There are no places to explore, and the tools it provides are either redundant to other options or replaces the more interesting choices. A stellar mod, but it simply does not work in this scenario.

7. Bewitchment similarly does not fit with the purpose of the modpack. HexxyCraft is more technical based, with a focus on automation and integrating the high-end tools of Hex Casting with Create and Botania. Bewitchment does not really have a strong niche here, being more focused on player empowerment and magic. Not to mention having a second flavor of True Names in the same modpack is bound to cause incredible trouble. Worldgen non-withstanding, once again.

8. Handcrafted is a tricky one, largely due to the wide variety of alternative furniture mods to consider (don't want to add redundant furniture). Definitely under consideration.
